export const seedUsers = [
  {
    id: 'seed-user-1',
    displayName: 'Ava Chen',
    email: 'ava.seed@example.com',
    skills: [
      { name: 'React', level: 'advanced' },
      { name: 'JavaScript', level: 'advanced' },
      { name: 'CSS', level: 'intermediate' },
    ],
    interests: ['web apps', 'accessibility'],
    availability: { days: ['Mon', 'Tue', 'Wed', 'Thu'], startHour: 18, endHour: 22 },
    experienceNote: 'Built 3 hackathon-winning frontends. Comfortable owning UI end to end.',
    portfolioLink: '',
    reputationScore: 4.8,
    verifiedBadge: true,
  },
  {
    id: 'seed-user-2',
    displayName: 'Marcus Lee',
    email: 'marcus.seed@example.com',
    skills: [
      { name: 'Python', level: 'advanced' },
      { name: 'Machine Learning', level: 'advanced' },
      { name: 'SQL', level: 'intermediate' },
    ],
    interests: ['ML research', 'data pipelines'],
    availability: { days: ['Mon', 'Wed', 'Fri', 'Sat', 'Sun'], startHour: 9, endHour: 13 },
    experienceNote: 'TA for intro ML course, published one workshop paper.',
    portfolioLink: '',
    reputationScore: 4.6,
    verifiedBadge: true,
  },
  {
    id: 'seed-user-3',
    displayName: 'Priya Nair',
    email: 'priya.seed@example.com',
    skills: [
      { name: 'Figma', level: 'advanced' },
      { name: 'UI/UX', level: 'advanced' },
      { name: 'Illustration', level: 'intermediate' },
    ],
    interests: ['product design', 'branding'],
    availability: { days: ['Tue', 'Thu', 'Sat'], startHour: 14, endHour: 18 },
    experienceNote: 'Freelance designer, led design for two class capstone projects.',
    portfolioLink: '',
    reputationScore: 4.9,
    verifiedBadge: false,
  },
  {
    id: 'seed-user-4',
    displayName: 'Diego Ramirez',
    email: 'diego.seed@example.com',
    skills: [
      { name: 'Node.js', level: 'advanced' },
      { name: 'PostgreSQL', level: 'intermediate' },
      { name: 'System Design', level: 'intermediate' },
    ],
    interests: ['backend infra', 'APIs'],
    availability: { days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], startHour: 19, endHour: 23 },
    experienceNote: 'Interned as backend engineer, built a small SaaS side project.',
    portfolioLink: '',
    reputationScore: 4.5,
    verifiedBadge: false,
  },
  {
    id: 'seed-user-5',
    displayName: 'Sofia Petrov',
    email: 'sofia.seed@example.com',
    skills: [
      { name: 'React', level: 'intermediate' },
      { name: 'Node.js', level: 'intermediate' },
      { name: 'MongoDB', level: 'beginner' },
    ],
    interests: ['full-stack apps', 'startups'],
    availability: { days: ['Wed', 'Thu', 'Fri', 'Sat', 'Sun'], startHour: 10, endHour: 16 },
    experienceNote: 'Self-taught full-stack dev, two shipped side projects.',
    portfolioLink: '',
    reputationScore: 4.3,
    verifiedBadge: false,
  },
  {
    id: 'seed-user-6',
    displayName: 'Kenji Watanabe',
    email: 'kenji.seed@example.com',
    skills: [
      { name: 'Python', level: 'intermediate' },
      { name: 'Pandas', level: 'intermediate' },
      { name: 'Data Visualization', level: 'beginner' },
    ],
    interests: ['data storytelling', 'sports analytics'],
    availability: { days: ['Sat', 'Sun'], startHour: 10, endHour: 20 },
    experienceNote: 'Day-scholar schedule — only free on weekends, but fully committed then.',
    portfolioLink: '',
    reputationScore: 4.2,
    verifiedBadge: false,
    isDayScholar: true,
  },
  {
    id: 'seed-user-7',
    displayName: 'Layla Haddad',
    email: 'layla.seed@example.com',
    skills: [
      { name: 'Machine Learning', level: 'intermediate' },
      { name: 'Python', level: 'advanced' },
      { name: 'System Design', level: 'beginner' },
    ],
    interests: ['NLP', 'research writing'],
    availability: { days: ['Mon', 'Tue', 'Wed'], startHour: 8, endHour: 11 },
    experienceNote: 'Research assistant in the NLP lab for two semesters.',
    portfolioLink: '',
    reputationScore: 4.7,
    verifiedBadge: true,
  },
  {
    id: 'seed-user-8',
    displayName: 'Tomás Silva',
    email: 'tomas.seed@example.com',
    skills: [
      { name: 'CSS', level: 'advanced' },
      { name: 'Figma', level: 'intermediate' },
      { name: 'JavaScript', level: 'beginner' },
    ],
    interests: ['design systems', 'motion design'],
    availability: { days: ['Mon', 'Thu', 'Fri'], startHour: 17, endHour: 21 },
    experienceNote: 'Design-leaning frontend student, strong visual eye.',
    portfolioLink: '',
    reputationScore: 4.4,
    verifiedBadge: false,
    isDayScholar: true,
  },
  {
    id: 'seed-user-9',
    displayName: 'Grace Okonkwo',
    email: 'grace.seed@example.com',
    skills: [
      { name: 'System Design', level: 'advanced' },
      { name: 'Node.js', level: 'advanced' },
      { name: 'SQL', level: 'advanced' },
    ],
    interests: ['scalable systems', 'venture building'],
    availability: { days: ['Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], startHour: 9, endHour: 21 },
    experienceNote: 'Previously co-founded a small campus startup, handles ambiguity well.',
    portfolioLink: '',
    reputationScore: 4.9,
    verifiedBadge: true,
  },
]

export const seedProjects = [
  {
    id: 'seed-project-1',
    title: 'Campus Events Hackathon App',
    description: 'A 48-hour hackathon build to help students discover campus events in real time.',
    contextType: 'hackathon',
    requiredSkills: ['React', 'Node.js', 'JavaScript'],
    commitmentLevel: 'Full weekend',
    timeline: '48 hours',
  },
  {
    id: 'seed-project-2',
    title: 'Data Structures Capstone Visualizer',
    description: 'Class project: an interactive visualizer for common data structures and algorithms.',
    contextType: 'class',
    requiredSkills: ['JavaScript', 'CSS', 'System Design'],
    commitmentLevel: '5 hrs/week',
    timeline: 'Sept-Dec',
  },
  {
    id: 'seed-project-3',
    title: 'NLP Sentiment Research Study',
    description: 'Research project analyzing sentiment trends in student forum posts using ML.',
    contextType: 'research',
    requiredSkills: ['Python', 'Machine Learning', 'Pandas'],
    commitmentLevel: '8 hrs/week',
    timeline: 'One semester',
  },
]

export const seedBoardPosts = [
  {
    authorId: 'seed-user-1',
    authorName: 'Ava Chen',
    text: 'Anyone else thinking about building an accessibility checker for student project sites? Half-formed idea, would love a partner.',
  },
  {
    authorId: 'seed-user-4',
    authorName: 'Diego Ramirez',
    text: 'Looking for someone who actually enjoys writing API docs. I do not. That is the whole post.',
  },
  {
    authorId: 'seed-user-6',
    authorName: 'Kenji Watanabe',
    text: 'Weekend hack idea: a dashboard that turns intramural sports stats into something actually fun to look at.',
  },
  {
    authorId: 'seed-user-9',
    authorName: 'Grace Okonkwo',
    text: 'If your project needs someone to think about scale before it is a problem, that is my favorite kind of Tuesday.',
  },
]

export const seedTopicPosts = {
  'climate-tech': [
    { authorId: 'seed-user-2', authorName: 'Marcus Lee', text: 'Any interest in a carbon-tracking widget for dorm energy usage?' },
    { authorId: 'seed-user-9', authorName: 'Grace Okonkwo', text: 'Would join if someone owns the data pipeline side.' },
  ],
  'generative-ai': [
    { authorId: 'seed-user-7', authorName: 'Layla Haddad', text: 'Curious if anyone has tried fine-tuning a small model on course notes for a study-buddy bot.' },
  ],
  'robotics-overflow': [
    { authorId: 'seed-user-4', authorName: 'Diego Ramirez', text: 'Robotics club overflow project needs a firmware person — anyone here done embedded C before?' },
  ],
  'hackathon-teammates': [
    { authorId: 'seed-user-1', authorName: 'Ava Chen', text: 'Free next hackathon weekend and looking for a team, frontend-heavy skillset.' },
    { authorId: 'seed-user-5', authorName: 'Sofia Petrov', text: 'Same! Full-stack, prefer small teams of 3-4.' },
  ],
}
